package com.yasin.farsitalkingclock;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import android.speech.tts.TextToSpeech;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root,list; TextView clock,date,status; View clockView; ScheduleStore store; Handler clockHandler=new Handler(Looper.getMainLooper()); boolean firstBuild=true;
    int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    float fs(float z){return z*UiTheme.fontScale(this);} TextView tv(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextColor(UiTheme.text(this));t.setTextSize(fs(z));t.setGravity(Gravity.CENTER_VERTICAL|Gravity.RIGHT);t.setPadding(dp(14),dp(5),dp(14),dp(5));return t;} LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}
    @Override public void onCreate(Bundle b){super.onCreate(b);store=new ScheduleStore(this);build();Scheduler.reschedule(this);clockHandler.post(tick);}
    @Override protected void onResume(){super.onResume();if(store!=null){build();refresh();updateClock();}}
    void applyBars(){int b=UiTheme.bg(this);getWindow().setStatusBarColor(b);getWindow().setNavigationBarColor(b);if(Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(UiTheme.getLightTheme(this)?View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR:0);}
    void build(){applyBars();root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(10),dp(14),dp(10));root.setBackgroundColor(UiTheme.bg(this));
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=tv("ساعت‌گوی",24);title.setTypeface(null,Typeface.BOLD);top.addView(title,lp(0,dp(56)));((LinearLayout.LayoutParams)title.getLayoutParams()).weight=1;Button settings=button("⚙",22,UiTheme.card(this));settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));top.addView(settings,lp(dp(58),dp(50)));root.addView(top);
        LinearLayout hero=new LinearLayout(this);hero.setOrientation(LinearLayout.VERTICAL);hero.setGravity(Gravity.CENTER);hero.setPadding(dp(8),dp(12),dp(8),dp(12));hero.setBackground(bg(UiTheme.surface(this),30));TextView small=tv("اعلام ساعت • English TTS",13);small.setGravity(Gravity.CENTER);small.setTextColor(Color.rgb(148,163,184));hero.addView(small,lp(-1,dp(28)));
        int style=store.getInt("clockStyle",0);clockView=createClock(style);hero.addView(clockView,lp(-1,dp(style==3?190:86)));date=tv("",15);date.setGravity(Gravity.CENTER);date.setTextColor(UiTheme.text(this));hero.addView(date,lp(-1,dp(32)));status=tv("● فعال",13);status.setGravity(Gravity.CENTER);hero.addView(status,lp(-1,dp(30)));root.addView(hero,lp(-1,dp(style==3?284:176)));
        LinearLayout quick=new LinearLayout(this);quick.setPadding(0,dp(10),0,dp(4));quick.setGravity(Gravity.CENTER);String[] q={"برنامه‌ها","تست صدا","تنظیمات"};for(String s:q){Button b=button(s,13,UiTheme.card(this));if(s.equals("تست صدا"))b.setOnClickListener(v->testSpeech());else if(s.equals("تنظیمات"))b.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));quick.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));Space sp=new Space(this);quick.addView(sp,lp(dp(7),1));}root.addView(quick,lp(-1,dp(58)));
        TextView h=tv("برنامه‌های سخنگو",20);h.setTypeface(null,Typeface.BOLD);h.setPadding(dp(8),dp(8),dp(8),dp(4));root.addView(h,lp(-1,dp(46)));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.addView(list);root.addView(sv,lp(-1,0));((LinearLayout.LayoutParams)sv.getLayoutParams()).weight=1;
        Button add=button("＋  افزودن برنامه سخنگوی جدید",16,UiTheme.accent(this));add.setOnClickListener(v->{Schedule s=new Schedule(store.nextId(),"اعلام ساعت",480,1320,60,true,127,"{time}",store.defaultRate(),store.defaultPitch());startActivity(new Intent(this,ScheduleEditorActivity.class).putExtra("id",s.id).putExtra("new",true));});root.addView(add,lp(-1,dp(58)));setContentView(root);refresh();}
    Button button(String s,float size,int color){Button b=new Button(this);b.setText(s);b.setTextSize(fs(size));b.setTextColor(UiTheme.text(this));b.setAllCaps(false);b.setIncludeFontPadding(false);b.setMinHeight(0);b.setMinimumHeight(0);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(10),dp(3),dp(10),dp(3));b.setBackground(bg(color,18));return b;}
    View createClock(int style){if(style==3){AnalogClockView a=new AnalogClockView(this);return a;}clock=new TextView(this);clock.setGravity(Gravity.CENTER);clock.setTextColor(UiTheme.text(this));clock.setTypeface(style==1||style==4?Typeface.MONOSPACE:Typeface.DEFAULT,Typeface.BOLD);clock.setTextSize(fs(style==2?40:48));clock.setIncludeFontPadding(false);if(Build.VERSION.SDK_INT>=21)clock.setLetterSpacing(style==1?.10f:.02f);if(style==4)clock.setBackground(bg(UiTheme.card(this),20));return clock;}
    void refresh(){if(list==null)return;list.removeAllViews();ArrayList<Schedule> all=store.all();if(all.isEmpty()){TextView e=tv("هنوز برنامه‌ای ساخته نشده است\nاز دکمه پایین اولین برنامه را بسازید.",15);e.setGravity(Gravity.CENTER);e.setTextColor(Color.rgb(148,163,184));list.addView(e,lp(-1,dp(110)));return;}for(Schedule s:all){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(10),dp(10),dp(10));card.setBackground(bg(UiTheme.card(this),22));LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.CENTER_VERTICAL);TextView name=tv(s.name,17);name.setTypeface(null,Typeface.BOLD);line.addView(name,new LinearLayout.LayoutParams(0,dp(34),1));Switch sw=new Switch(this);sw.setChecked(s.enabled);sw.setOnCheckedChangeListener((v,c)->{s.enabled=c;store.save(store.all());Scheduler.reschedule(this);});line.addView(sw,lp(dp(58),dp(42)));card.addView(line);TextView meta=tv(fmt(s.startMin)+"  تا  "+fmt(s.endMin)+"   •   هر "+PersianTime.digits(""+s.intervalMin)+" دقیقه",13);meta.setTextColor(Color.rgb(148,163,184));card.addView(meta,lp(-1,dp(28)));TextView d=tv("روزها: "+days(s.daysMask)+(s.customText.trim().isEmpty()?"":"   •   متن سفارشی"),12);d.setTextColor(UiTheme.accent(this));card.addView(d,lp(-1,dp(28)));card.setOnClickListener(v->startActivity(new Intent(this,ScheduleEditorActivity.class).putExtra("id",s.id)));list.addView(card,lp(-1,dp(112)));Space sp=new Space(this);list.addView(sp,lp(1,dp(8)));}}
    String days(int m){String[] n={"د","س","چ","پ","ج","ش","ی"};StringBuilder b=new StringBuilder();for(int i=0;i<7;i++)if((m&(i==6?64:1<<i))!=0)b.append(n[i]).append(' ');return b.toString().trim();}
    String fmt(int m){return PersianTime.digits(String.format(Locale.US,"%02d:%02d",m/60,m%60));}
    void testSpeech(){final TextToSpeech[] t={null};final ScheduleStore s=new ScheduleStore(this);final TextToSpeech.OnInitListener l=new TextToSpeech.OnInitListener(){@Override public void onInit(int status){if(status==TextToSpeech.SUCCESS){t[0].setLanguage(Locale.US);t[0].setSpeechRate(s.defaultRate());t[0].setPitch(s.defaultPitch());t[0].speak("This is a test of the selected English speech engine.",TextToSpeech.QUEUE_FLUSH,null,"test");}}};String e=s.getTtsEnginePackage(this);if(e==null)t[0]=new TextToSpeech(this,l);else t[0]=new TextToSpeech(this,l,e);}
    Runnable tick=new Runnable(){public void run(){updateClock();clockHandler.postDelayed(this,1000);}};
    void updateClock(){Calendar c=Calendar.getInstance();int style=store.getInt("clockStyle",0);String text=String.format(Locale.US,store.getInt("hourFormat",0)==1?"%02d:%02d:%02d":"%02d:%02d:%02d",c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),c.get(Calendar.SECOND));if(style!=3&&clock!=null){if(!store.getBool("showSeconds",true))text=text.substring(0,5);clock.setText(text);clock.setTextColor(UiTheme.text(this));clock.setTextSize(fs(style==2?40:48));}if(clockView instanceof AnalogClockView)((AnalogClockView)clockView).setNow(c);if(date!=null)date.setText(new SimpleDateFormat("EEEE، d MMMM",new Locale("fa","IR")).format(c.getTime()));if(status!=null){boolean sil=store.silentNow(c);status.setText(sil?"● سکوت شبانه":"● برنامه فعال است");status.setTextColor(sil?Color.rgb(251,191,36):Color.rgb(74,222,128));}}
    @Override protected void onDestroy(){clockHandler.removeCallbacks(tick);super.onDestroy();}
}
