package com.yasin.farsitalkingclock;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.util.*;

public class ScheduleEditorActivity extends Activity{
 ScheduleStore st; Schedule s; LinearLayout root,body; int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 TextView t(String x,float z){TextView v=new TextView(this);v.setText(x);v.setTextColor(Color.WHITE);v.setTextSize(z);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);v.setPadding(dp(12),dp(5),dp(12),dp(5));return v;}
 @Override public void onCreate(Bundle b){super.onCreate(b);st=new ScheduleStore(this);int id=getIntent().getIntExtra("id",-1);s=null;for(Schedule x:st.all())if(x.id==id)s=x;if(s==null){s=new Schedule(id<0?st.nextId():id,"اعلام ساعت",480,1320,60,true,127,"{time}",st.defaultRate(),st.defaultPitch());ArrayList<Schedule>a=st.all();a.add(s);st.save(a);}build();}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(7,12,25));root.setPadding(dp(12),dp(8),dp(12),0);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);Button back=new Button(this);back.setText("‹");back.setTextColor(Color.WHITE);back.setTextSize(30);back.setBackground(bg(Color.rgb(18,30,52),16));back.setOnClickListener(v->finish());bar.addView(back,new LinearLayout.LayoutParams(dp(54),dp(50)));TextView title=t("ویرایش برنامه سخنگو",19);title.setTypeface(null,Typeface.BOLD);bar.addView(title,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(bar);
  ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(0,dp(8),0,dp(20));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  section("اطلاعات برنامه");EditText name=edit("نام برنامه",s.name);body.addView(name,lp(-1,dp(58)));
  section("فعال‌سازی");Switch enabled=sw("این برنامه فعال باشد",s.enabled);body.addView(enabled,lp(-1,dp(52)));
  section("بازه زمانی");final int[] startValue={s.startMin}, endValue={s.endMin};
  Button start=timeField("ساعت شروع",startValue[0],v->{startValue[0]=v;}); Button end=timeField("ساعت پایان",endValue[0],v->{endValue[0]=v;});
  body.addView(start,lp(-1,dp(54))); body.addView(end,lp(-1,dp(54)));
  section("تکرار و روزهای هفته");LinearLayout dayRow=new LinearLayout(this);dayRow.setGravity(Gravity.CENTER);String[] dn={"د","س","چ","پ","ج","ش","ی"};CheckBox[] cb=new CheckBox[7];for(int i=0;i<7;i++){cb[i]=new CheckBox(this);cb[i].setText(dn[i]);cb[i].setTextColor(Color.WHITE);cb[i].setTextSize(13);cb[i].setGravity(Gravity.CENTER);cb[i].setChecked((s.daysMask&(i==6?64:1<<i))!=0);dayRow.addView(cb[i],new LinearLayout.LayoutParams(0,dp(52),1));}body.addView(dayRow,lp(-1,dp(58)));
  EditText interval=edit("فاصله اعلام (دقیقه)",""+s.intervalMin);interval.setInputType(2);body.addView(interval,lp(-1,dp(58)));
  section("متن سفارشی (برای موتور English)");EditText custom=edit("متن اعلام؛ مثال: الان {time}",s.customText);custom.setSingleLine(false);custom.setMinLines(3);custom.setGravity(Gravity.TOP|Gravity.RIGHT);body.addView(custom,lp(-1,dp(100)));TextView vars=t("متغیرها: {time} ساعت کامل • {hour} ساعت • {minute} دقیقه • {second} ثانیه • {date} تاریخ • {day} روز هفته",12);vars.setTextColor(Color.rgb(96,165,250));body.addView(vars,lp(-1,dp(60)));
  section("تنظیمات صدا برای همین برنامه");SeekBar rate=new SeekBar(this);rate.setMax(100);rate.setProgress((int)((s.speechRate-.5f)/1.5f*100));body.addView(t("سرعت گفتار: "+String.format(Locale.US,"%.1fx",s.speechRate),13));body.addView(rate,lp(-1,dp(48)));SeekBar pitch=new SeekBar(this);pitch.setMax(100);pitch.setProgress((int)((s.pitch-.5f)/1.5f*100));body.addView(t("تُن صدا: "+String.format(Locale.US,"%.1f",s.pitch),13));body.addView(pitch,lp(-1,dp(48)));rate.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean f){s.speechRate=.5f+1.5f*p/100f;}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});pitch.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean f){s.pitch=.5f+1.5f*p/100f;}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});
  section("گزینه‌های پیشرفته");Switch announceDate=sw("اعلام تاریخ همراه ساعت",false);body.addView(announceDate,lp(-1,dp(50)));Switch announceSeconds=sw("اعلام ثانیه در متن سفارشی",false);body.addView(announceSeconds,lp(-1,dp(50)));Switch vibrate=sw("لرزش کوتاه هنگام اعلام",false);body.addView(vibrate,lp(-1,dp(50)));
  LinearLayout actions=new LinearLayout(this);actions.setPadding(0,dp(12),0,0);Button test=new Button(this);test.setText("▶ تست صدا");test.setTextColor(Color.WHITE);test.setAllCaps(false);test.setBackground(bg(Color.rgb(30,64,175),20));test.setOnClickListener(v->test(custom.getText().toString()));actions.addView(test,new LinearLayout.LayoutParams(0,dp(54),1));Space sp=new Space(this);actions.addView(sp,lp(dp(8),1));Button save=new Button(this);save.setText("ذخیره برنامه");save.setTextColor(Color.WHITE);save.setAllCaps(false);save.setBackground(bg(Color.rgb(37,99,235),20));save.setOnClickListener(v->{s.name=name.getText().toString().trim();if(s.name.isEmpty())s.name="اعلام ساعت";s.enabled=enabled.isChecked();s.startMin=startValue[0];s.endMin=endValue[0];try{s.intervalMin=Math.max(1,Integer.parseInt(interval.getText().toString()));}catch(Exception e){s.intervalMin=60;}s.customText=custom.getText().toString();int mask=0;for(int i=0;i<7;i++)if(cb[i].isChecked())mask|=(i==6?64:1<<i);s.daysMask=mask;ArrayList<Schedule>a=st.all();boolean f=false;for(int i=0;i<a.size();i++)if(a.get(i).id==s.id){a.set(i,s);f=true;}if(!f)a.add(s);st.save(a);Scheduler.reschedule(this);finish();});actions.addView(save,new LinearLayout.LayoutParams(0,dp(54),2));body.addView(actions,lp(-1,dp(66)));
  Button del=new Button(this);del.setText("حذف این برنامه");del.setTextColor(Color.rgb(248,113,113));del.setAllCaps(false);del.setBackground(bg(Color.rgb(55,25,34),20));del.setOnClickListener(v->{ArrayList<Schedule>a=st.all();for(int i=a.size()-1;i>=0;i--)if(a.get(i).id==s.id)a.remove(i);st.save(a);Scheduler.reschedule(this);finish();});body.addView(del,lp(-1,dp(52)));setContentView(root);
 }
 LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}void section(String s){TextView v=t(s,15);v.setTypeface(null,Typeface.BOLD);v.setTextColor(Color.rgb(96,165,250));v.setPadding(dp(10),dp(18),dp(10),dp(8));body.addView(v,lp(-1,dp(46)));}
 EditText edit(String hint,String val){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(100,116,139));e.setTextColor(Color.WHITE);e.setText(val);e.setTextSize(14);e.setPadding(dp(14),0,dp(14),0);e.setBackground(bg(Color.rgb(17,27,49),18));return e;}
 Switch sw(String text,boolean checked){Switch x=new Switch(this);x.setText(text);x.setTextColor(Color.WHITE);x.setTextSize(12);x.setChecked(checked);x.setPadding(dp(10),0,dp(8),0);return x;}
 Button timeField(String label,int value,final IntSaver saver){Button b=new Button(this);b.setText(label+"\n"+fmtTime(value));b.setTextColor(Color.WHITE);b.setTextSize(14);b.setAllCaps(false);b.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);b.setPadding(dp(14),0,dp(14),0);b.setBackground(bg(Color.rgb(17,27,49),18));b.setTag(value);b.setOnClickListener(v->{int current=(Integer)b.getTag();int h=current/60,m=current%60;TimePickerDialog d=new TimePickerDialog(this,(view,hh,mm)->{int n=hh*60+mm;saver.save(n);b.setTag(n);b.setText(label+"\n"+fmtTime(n));},h,m,true);d.setTitle(label);d.show();});return b;}
 interface IntSaver{void save(int value);}
 String fmtTime(int m){return PersianTime.digits(String.format(Locale.US,"%02d:%02d",m/60,m%60));}
 void test(String custom){final android.speech.tts.TextToSpeech[] t={null};final Calendar c=Calendar.getInstance();final String txt=custom.trim().isEmpty()?ClockReceiver.spokenEnglish(c):ClockReceiver.expandEnglish(custom,c);final android.speech.tts.TextToSpeech.OnInitListener l=new android.speech.tts.TextToSpeech.OnInitListener(){@Override public void onInit(int status){if(status==android.speech.tts.TextToSpeech.SUCCESS){t[0].setLanguage(Locale.US);t[0].setSpeechRate(s.speechRate);t[0].setPitch(s.pitch);t[0].speak(txt,android.speech.tts.TextToSpeech.QUEUE_FLUSH,null,"preview");}}};String e=st.getTtsEnginePackage(this);if(e==null)t[0]=new android.speech.tts.TextToSpeech(this,l);else t[0]=new android.speech.tts.TextToSpeech(this,l,e);}
}
