plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yasin.farsitalkingclock'
    compileSdk 35
    defaultConfig {
        applicationId 'com.yasin.farsitalkingclock'
        minSdk 23
        targetSdk 35
        versionCode 12
        versionName '1.8.1'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
